### ISSUE TITLE
hidden window consumes mouse event

### ISSUE THREAD

**Issue by francmarx** [keharriso/love-nuklear#16]
Hi,
if a window is switch to hidden state ( nk.windowHide('Skin Example') )
it still consumes the mouse events if mouse is over the window area.
Franc

**Comment by vurtun** [comment]
Thanks for another issue. This was another bug in my main nuklear code, not such much the fault of love-nuklear. Should now be fixed in commit: vurtun/nuklear@6f8fe8d05b20c0ef729a40b6ec03c01d0c9392d9.

@keharriso If you want you can directly refer these issues back to me if you want so you don't have to handle my bugs.
